name: 'DocAlign'
description: 'Check documentation-code alignment on pull requests'
branding:
  icon: 'file-text'
  color: 'blue'

# Required permissions in workflow:
# permissions:
#   pull-requests: write  # For posting/updating PR comments

inputs:
  github-token:
    description: 'GitHub token for posting PR comments and annotations'
    required: false
    default: ${{ github.token }}
  anthropic-api-key:
    description: 'Anthropic API key for LLM verification (optional, enables Tier 3)'
    required: false
  min-severity:
    description: 'Minimum severity to report (high, medium, low)'
    required: false
    default: 'medium'
  exclude:
    description: 'Comma-separated file patterns to exclude'
    required: false
  fail-on-drift:
    description: 'Fail the check if any drift is found'
    required: false
    default: 'true'
  docalign-version:
    description: 'DocAlign version to install (default: latest)'
    required: false
    default: 'latest'

outputs:
  health:
    description: 'Documentation health percentage'
  verified:
    description: 'Number of verified claims'
  drifted:
    description: 'Number of drifted claims'

runs:
  using: 'composite'
  steps:
    - name: Install DocAlign
      shell: bash
      run: npm install -g docalign@${{ inputs.docalign-version }}

    - name: Run DocAlign scan
      id: scan
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        DOCALIGN_EXCLUDE: ${{ inputs.exclude }}
        DOCALIGN_MIN_SEVERITY: ${{ inputs.min-severity }}
      run: |
        EXCLUDE_ARG=""
        if [ -n "$DOCALIGN_EXCLUDE" ]; then
          EXCLUDE_ARG="--exclude=$DOCALIGN_EXCLUDE"
        fi

        MIN_SEV_ARG=""
        if [ -n "$DOCALIGN_MIN_SEVERITY" ]; then
          MIN_SEV_ARG="--min-severity=$DOCALIGN_MIN_SEVERITY"
        fi

        # Run scan with JSON output, capture exit code
        set +e
        OUTPUT=$(docalign scan $EXCLUDE_ARG $MIN_SEV_ARG --json 2>&1)
        EXIT_CODE=$?
        set -e

        # Write output for next step
        echo "$OUTPUT" > /tmp/docalign-output.json

        # Parse health metrics from JSON
        if echo "$OUTPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(f'health={d[\"healthPercent\"]}\nverified={d[\"verified\"]}\ndrifted={d[\"drifted\"]}')" >> "$GITHUB_OUTPUT" 2>/dev/null; then
          echo "Parsed scan results"
        else
          echo "health=0" >> "$GITHUB_OUTPUT"
          echo "verified=0" >> "$GITHUB_OUTPUT"
          echo "drifted=0" >> "$GITHUB_OUTPUT"
        fi

        # Generate PR comment markdown
        docalign scan $EXCLUDE_ARG --format github-pr > /tmp/docalign-pr-comment.md 2>&1 || true

    - name: Post PR Comment
      if: github.event_name == 'pull_request'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        node "${{ github.action_path }}/post-comment.mjs"

    - name: Check drift threshold
      if: inputs.fail-on-drift == 'true'
      shell: bash
      run: |
        DRIFTED="${{ steps.scan.outputs.drifted }}"
        if [ "$DRIFTED" -gt "0" ] 2>/dev/null; then
          echo "::error::DocAlign found $DRIFTED documentation drift issue(s)."
          exit 1
        fi
