# DocAlign configuration for the DocAlign repository itself.
# https://docalign.dev/docs/reference/configuration

doc_patterns:
  # Root-level planning/ops docs are excluded from scanning.
  # They contain task checklists, planning notes, and file references to
  # files that may no longer exist — not factual claims about the codebase.
  exclude:
    - "EXEC_PLAN.md"
    - "PLAN-MCP-GAPS.md"
    - "PRD.md"
    - "AUTONOMOUS-OS.md"
    - "KICKOFF-PROMPT.md"
    - "PRODUCT-VISION.md"
    - "_team/**"
    - "phases/**"
    - "tasks/**"

