# Epic Pipeline — Autonomous OS
#
# CEO involvement: decision doc approval, decomposition approval, ship notification ONLY.
# Everything between decomposition approval and ship is FULLY AUTONOMOUS.
# Child feature/task pipelines follow their own autonomy rules.
#
# Flow:
#   Signal → Strategic Debate → CEO Approves Decision
#   → Decompose → CEO Approves Decomposition → QA Integration Tests
#   → Execute Children (autonomous) → Integration Review (automated)
#   → Verification → GTM Content → Ship → CEO Notified
#
# Key design principles:
# - CEO approves strategic direction (debate decision doc) and decomposition plan.
# - All child pipelines (features/tasks) run with their own autonomy rules.
# - Integration review, GTM, and ship are fully autonomous.
# - CEO is notified at ship with comprehensive summary.

name: epic
description: Multi-feature epic pipeline — autonomous after decomposition approval

stages:
  - id: signal
    description: Epic signal received from CEO
    type: entry
    next: strategic_debate_round1

  # --- STRATEGIC DEBATE ---

  - id: strategic_debate_round1
    description: "Full team strategic assessment: PM, Tech Lead, Critic, GTM"
    type: review
    reviewers:
      - agent: pm
      - agent: tech-lead
      - agent: critic
      - agent: gtm
    parallel: true
    parallel_group: strategic_debate_r1
    on_converge: ceo_decision_approval
    on_diverge: strategic_debate_round2

  - id: strategic_debate_round2
    description: "Targeted resolution for strategic disagreements"
    type: review
    reviewers: dynamic
    parallel: true
    parallel_group: strategic_debate_r2
    on_converge: ceo_decision_approval
    on_diverge: escalate_debate

  - id: escalate_debate
    description: Strategic debate unresolved — CEO decides
    type: escalation
    notify: ceo
    next_on_build: ceo_decision_approval
    next_on_kill: done

  # --- CEO DECISION APPROVAL ---

  - id: ceo_decision_approval
    description: "CEO approves strategic direction and decision doc"
    type: approval
    approver: ceo
    notify: ceo
    on_approve: decompose
    on_reject: strategic_debate_round1
    on_kill: done

  # --- DECOMPOSE ---

  - id: decompose
    description: PM + Tech Lead break epic into features and tasks with execution plan
    type: work
    agents:
      - pm
      - tech-lead
    parallel: true
    parallel_group: decompose
    # Output: ordered list of features and tasks with dependencies,
    # session estimates, and priority order.
    next: ceo_decompose_approval

  # --- CEO DECOMPOSITION APPROVAL (last human gate) ---

  - id: ceo_decompose_approval
    description: "CEO approves decomposition plan. LAST human gate before autonomous execution."
    type: approval
    approver: ceo
    notify: ceo
    on_approve: qa_integration_tests
    on_reject: decompose
    on_kill: done

  # --- QA INTEGRATION TESTS (pre-execution test writing) ---

  - id: qa_integration_tests
    description: "QA writes integration tests verifying child features work together"
    type: work
    agent: qa
    autonomous: true
    # Inputs: decompose/pm.md, decompose/tech-lead.md, decision.md
    # Outputs: outputs/<run_id>/qa_integration_tests/qa.md + files/test/qa/integration/...
    # Focus: cross-feature contracts, shared interfaces, data flow between children
    next: execute_children

  # --- EXECUTE CHILDREN (fully autonomous from here) ---

  - id: execute_children
    description: "Child feature/task pipelines run concurrently — fully autonomous"
    type: fan_out
    autonomous: true
    # Orchestrator creates child pipeline runs via pipeline skill
    # Each child gets its own git worktree (managed by pipeline.js)
    # Each child follows its own pipeline autonomy rules
    # Tracks all children via parent_epic_id
    # Waits for all children to complete
    on_all_complete: integration_review
    on_any_failed: escalate_children

  - id: escalate_children
    description: One or more child pipelines failed — escalate (exceptional)
    type: escalation
    notify: ceo
    next: integration_review

  # --- INTEGRATION REVIEW (automated, NOT CEO) ---

  - id: integration_review
    description: "Automated: Tech Lead + Critic review the integrated whole"
    type: review
    reviewers:
      - agent: tech-lead
      - agent: critic
    parallel: true
    parallel_group: integration_review
    max_loops: 3
    autonomous: true
    on_approve: verify
    on_reject: escalate_integration
    on_max_loops: escalate_integration

  - id: escalate_integration
    description: Integration issues found — escalate to CEO (exceptional)
    type: escalation
    notify: ceo
    next: verify

  # --- VERIFICATION (automated) ---

  - id: verify
    description: "Verify all child features integrated, CI green, acceptance criteria met"
    type: work
    agent: tech-lead
    autonomous: true
    on_pass: gtm_content
    on_fail: escalate_integration

  # --- GTM + SHIP (autonomous) ---

  - id: gtm_content
    description: "GTM creates launch content — autonomous, no CEO review"
    type: work
    agent: gtm
    autonomous: true
    next: ship

  - id: ship
    description: "Epic shipped — notify CEO with comprehensive summary"
    type: terminal
    status: completed
    actions:
      - store_memories
      - notify_ceo
    # CEO notification includes:
    #   - Strategic summary
    #   - All child features completed
    #   - PR links and CI results
    #   - Integration review outcome
    #   - GTM content links
    #   - Follow-up items

  - id: done
    description: Epic killed or completed
    type: terminal
    status: completed
