# Feature Pipeline — Autonomous OS
#
# CEO involvement: decision doc approval, spec approval, ship notification ONLY.
# Everything between spec approval and ship is FULLY AUTONOMOUS.
#
# Flow:
#   Signal → Debate → Define → Spec → Spec Review → CEO Approves Spec
#   → Plan → QA Tests → Build (via Claude Code / Codex CLI) → CI/CD
#   → Code Review (automated) → Verification → GTM Content → Ship → CEO Notified
#
# Key design principles:
# - CEO is NOT asked to approve build, build_review, gtm, or content.
# - Build uses external coding tools (claude CLI or codex CLI), NOT agent self-coding.
# - Git worktree created automatically by pipeline.js for build isolation.
# - Build pushes to git, runs CI, iterates on failures autonomously.
# - Code review is automated by agent personas, not CEO.
# - Verify stage rebases onto main, resolves conflicts, and merges PR.
# - Plan stage produces task breakdown referencing spec — build follows it.
# - Ship only happens after all checks pass and verification against spec.
# - Worktree is cleaned up automatically on pipeline completion.

name: feature
description: Full feature pipeline — autonomous after spec approval

stages:
  - id: signal
    description: Feature signal received and classified
    type: entry
    next: debate_round1

  # --- DEBATE PHASE ---

  - id: debate_round1
    description: "Parallel assessment: PM, Tech Lead, Critic, GTM evaluate the signal"
    type: review
    reviewers:
      - agent: pm
      - agent: tech-lead
      - agent: critic
      - agent: gtm
    parallel: true
    parallel_group: debate_r1
    on_converge: define
    on_diverge: debate_round2

  - id: debate_round2
    description: "Targeted resolution: only disagreeing agents re-assess with full context"
    type: review
    reviewers: dynamic
    parallel: true
    parallel_group: debate_r2
    on_converge: define
    on_diverge: escalate_debate

  - id: escalate_debate
    description: Debate unresolved after 2 rounds — escalate to CEO
    type: escalation
    notify: ceo
    next_on_build: define
    next_on_kill: done

  # --- DEFINE PHASE ---

  - id: define
    description: PM defines acceptance criteria, scope boundaries, definition of done
    type: work
    agent: pm
    next: spec

  # --- SPEC PHASE ---

  - id: spec
    description: Tech Lead writes technical specification
    type: work
    agent: tech-lead
    next: spec_review

  - id: spec_review
    description: "PM + Critic review the spec in parallel"
    type: review
    reviewers:
      - agent: pm
      - agent: critic
    parallel: true
    parallel_group: spec_review
    max_loops: 3
    on_approve: ceo_spec_approval
    on_reject: spec
    on_max_loops: escalate_spec

  - id: escalate_spec
    description: Spec review failed after 3 loops — escalate to CEO
    type: escalation
    notify: ceo
    next: ceo_spec_approval

  # --- CEO SPEC APPROVAL (last CEO gate before autonomous execution) ---

  - id: ceo_spec_approval
    description: "CEO reviews and approves spec. LAST human gate before autonomous build."
    type: approval
    approver: ceo
    notify: ceo
    # Send CEO: decision doc + spec + define artifacts + review feedback
    # CEO can approve, request changes, or kill
    on_approve: plan
    on_reject: spec
    on_kill: done

  # --- PLAN PHASE (task breakdown) ---

  - id: plan
    description: "Tech Lead breaks spec into execution plan with ordered tasks, dependencies, and session estimates"
    type: work
    agent: tech-lead
    # Produces: tasks/feature-<id>.md with numbered tasks, dependencies, files affected,
    # test criteria per task, and session groupings (like tasks/EXECUTION-PLAN.md pattern).
    # Build stage follows this plan task-by-task.
    next: qa_tests

  # --- QA TEST STAGE (pre-build test writing) ---

  - id: qa_tests
    description: "QA writes acceptance/contract tests based on spec, plan, and acceptance criteria"
    type: work
    agent: qa
    autonomous: true
    # Inputs: define/pm.md, spec/tech-lead.md, plan/tech-lead.md, decision.md
    # Outputs: outputs/<run_id>/qa_tests/qa.md (manifest) + qa_tests/files/test/qa/<slug>/...
    next: build

  # --- BUILD PHASE (fully autonomous from here) ---
  # Uses external coding tools (claude CLI or codex CLI), NOT agent self-coding.
  # Creates feature branch, pushes code, runs CI, iterates on failures.

  - id: build
    description: "Autonomous build in git worktree via Claude Code / Codex CLI"
    type: work
    agent: tech-lead
    autonomous: true  # No CEO involvement
    generate_handoff: true
    # Worktree created automatically by pipeline.js advance --stage build
    # All work happens in the worktree (NEVER in main repo)
    # Build agent uses worktree path from advance response
    # After all tasks: push branch, open PR
    next: code_review

  # --- CODE REVIEW (automated by agents, NOT CEO) ---

  - id: code_review
    description: "Automated code review: PM + Tech Lead + Critic review the PR"
    type: review
    reviewers:
      - agent: pm
      - agent: tech-lead
      - agent: critic
    parallel: true
    parallel_group: code_review
    max_loops: 3
    autonomous: true  # No CEO involvement
    on_approve: verify
    on_reject: build  # Iterate: fix issues, re-push, re-review
    on_max_loops: escalate_build

  - id: escalate_build
    description: "Build/review failed after 3 loops — escalate to CEO (exceptional)"
    type: escalation
    notify: ceo
    next: verify

  # --- VERIFICATION (automated) ---

  - id: verify
    description: "Verify implementation against spec: all acceptance criteria, CI green, tests pass"
    type: work
    agent: tech-lead
    autonomous: true
    # Checklist:
    #   1. All acceptance criteria from define stage are met
    #   2. All tasks from plan stage are completed
    #   3. CI pipeline passes (typecheck, lint, test)
    #   4. Rebase onto main, resolve conflicts if any
    #   5. Merge PR to main (squash)
    #   6. No regressions in existing tests
    #   7. Evidence artifacts collected
    # If verification fails: loop back to build with specific failures
    on_pass: gtm_content
    on_fail: build

  # --- GTM PHASE (autonomous) ---

  - id: gtm_content
    description: "GTM creates content (blog, tweets, demo plan) — autonomous, no CEO review"
    type: work
    agent: gtm
    autonomous: true
    next: ship

  # --- SHIP ---

  - id: ship
    description: "Feature shipped — notify CEO with summary of what was built, tested, and deployed"
    type: terminal
    status: completed
    actions:
      - store_memories
      - notify_ceo
      # Worktree cleanup is automatic via pipeline.js complete-run
    # CEO notification includes:
    #   - What was built (summary)
    #   - PR link
    #   - CI/test results
    #   - Verification evidence
    #   - GTM content links (if applicable)
    #   - Any open items or follow-ups

  - id: done
    description: Feature killed or completed without shipping
    type: terminal
    status: completed
    # Worktree cleanup is automatic via pipeline.js complete-run
