# Task Pipeline — Autonomous OS
#
# CEO involvement: NONE (unless escalated).
# Tasks are fully autonomous from start to finish.
#
# Flow:
#   Request → [Research?] → Task Define → QA Tests
#   → Build (via Claude Code / Codex CLI) → CI/CD → Code Review (automated)
#   → Verify → Done → CEO Notified
#
# Key design principles:
# - Build uses external coding tools (claude CLI or codex CLI), NOT agent self-coding.
# - Git worktree created automatically by pipeline.js for build isolation.
# - Build pushes to git, runs CI, iterates on failures autonomously.
# - Verify stage rebases onto main, resolves conflicts, and merges PR.
# - Code review is automated by Critic, not CEO.
# - Worktree is cleaned up automatically on pipeline completion.
# - CEO is only notified when task is done or escalated.

name: task
description: Simple task pipeline — fully autonomous

stages:
  - id: request
    description: Initial request received and classified
    type: entry
    next: research_check

  - id: research_check
    description: Determine if research is needed before building
    type: decision
    agent: orchestrator
    next_if_yes: research
    next_if_no: task_define

  - id: research
    description: Optional investigation phase
    type: work
    agent: researcher
    next: task_define

  # --- TASK DEFINE + QA TESTS ---

  - id: task_define
    description: "Orchestrator writes brief acceptance criteria from task request"
    type: work
    agent: orchestrator
    autonomous: true
    # Produces: outputs/<run_id>/task_define/orchestrator.md
    # Lightweight: 3-5 bullet-point acceptance criteria derived from the task title + research
    next: qa_tests

  - id: qa_tests
    description: "QA writes lightweight acceptance tests for the task"
    type: work
    agent: qa
    autonomous: true
    # Inputs: outputs/<run_id>/task_define/orchestrator.md, optional research output
    # Outputs: outputs/<run_id>/qa_tests/qa.md (manifest) + qa_tests/files/test/qa/...
    next: build

  # --- BUILD PHASE ---
  # Uses external coding tools (claude CLI or codex CLI), NOT agent self-coding.
  # Worktree created automatically by pipeline.js advance --stage build.
  # All work happens in the worktree (NEVER in main repo).

  - id: build
    description: "Autonomous build in git worktree via Claude Code / Codex CLI"
    type: work
    agent: tech-lead
    autonomous: true
    # Worktree created automatically by pipeline.js advance --stage build
    # Build agent uses worktree path from advance response
    # After task complete: push branch, open PR
    next: code_review

  # --- CODE REVIEW (automated, NOT CEO) ---

  - id: code_review
    description: "Automated code review: Critic reviews the PR"
    type: review
    reviewers:
      - agent: critic
    parallel: false
    max_loops: 2
    autonomous: true
    on_approve: verify
    on_reject: build
    on_max_loops: escalate

  # --- VERIFICATION ---

  - id: verify
    description: "Verify: CI green, tests pass, rebase + merge PR to main"
    type: work
    agent: tech-lead
    autonomous: true
    # 1. Confirm CI passes
    # 2. Rebase onto main, resolve conflicts if any
    # 3. Merge PR (squash)
    # 4. Collect evidence
    on_pass: done
    on_fail: build

  - id: done
    description: Task completed — notify CEO
    type: terminal
    status: completed
    actions:
      - store_memories
      - notify_ceo
    # CEO notification: what was done, PR link, test results

  - id: escalate
    description: Escalated to CEO after max review loops
    type: escalation
    notify: ceo
    next: verify  # CEO can force-approve
