# Task Pipeline — Autonomous OS
#
# CEO involvement: NONE (unless escalated).
# Tasks are fully autonomous from start to finish.
#
# Flow:
#   Request → [Research?] → Build (via Claude Code / Codex CLI)
#   → CI/CD → Code Review (automated) → Verify → Done → CEO Notified
#
# Key design principles:
# - Build uses external coding tools (claude CLI or codex CLI), NOT agent self-coding.
# - Build pushes to git, runs CI, iterates on failures autonomously.
# - Code review is automated by Critic, not CEO.
# - CEO is only notified when task is done or escalated.

name: task
description: Simple task pipeline — fully autonomous

stages:
  - id: request
    description: Initial request received and classified
    type: entry
    next: research_check

  - id: research_check
    description: Determine if research is needed before building
    type: decision
    agent: orchestrator
    next_if_yes: research
    next_if_no: build

  - id: research
    description: Optional investigation phase
    type: work
    agent: researcher
    next: build

  # --- BUILD PHASE ---
  # Uses external coding tools (claude CLI or codex CLI), NOT agent self-coding.
  # Creates branch, pushes code, runs CI, iterates on failures.

  - id: build
    description: "Autonomous build: execute task via Claude Code / Codex CLI"
    type: work
    agent: tech-lead
    autonomous: true
    # 1. Call claude/codex CLI with task context
    # 2. Run typecheck + lint + tests
    # 3. Commit on success
    # 4. If CI fails, iterate (call coding tool again to fix)
    # 5. Push branch, open PR
    next: code_review

  # --- CODE REVIEW (automated, NOT CEO) ---

  - id: code_review
    description: "Automated code review: Critic reviews the PR"
    type: review
    reviewers:
      - agent: critic
    parallel: false
    max_loops: 2
    autonomous: true
    on_approve: verify
    on_reject: build
    on_max_loops: escalate

  # --- VERIFICATION ---

  - id: verify
    description: "Verify: CI green, tests pass, PR merged"
    type: work
    agent: tech-lead
    autonomous: true
    # 1. Confirm CI passes
    # 2. Merge PR
    # 3. Collect evidence
    on_pass: done
    on_fail: build

  - id: done
    description: Task completed — notify CEO
    type: terminal
    status: completed
    actions:
      - store_memories
      - notify_ceo
    # CEO notification: what was done, PR link, test results

  - id: escalate
    description: Escalated to CEO after max review loops
    type: escalation
    notify: ceo
    next: verify  # CEO can force-approve
